version: "3.8"
services:
  #itest:
  #  image: fc-retrieval-itest:dev
  #  container_name: itest
  #  networks:
  #    - shared
  #  depends_on: 
  #    - gateway
                
  gateway:
    image: fc-retrieval-gateway:dev
    container_name: gateway
    networks:
      - shared
    env_file:
      - gateway.env
    ports:
      - "20000:${BIND_REST_API}"
      - "${BIND_PROVIDER_API}"
      - "${BIND_GATEWAY_API}"
      - "20001:${BIND_ADMIN_API}"

  provider:
    image: consensys/fc-retrieval-provider:dev
    container_name: provider
    networks:
      - shared
    ports:
      - "20002:80"
    env_file:
      - provider.env

  register:
    image: consensys/fc-retrieval-register:dev
    ports:
      - "80"
    volumes:
      - ./:/app
    networks:
      - shared
    restart: unless-stopped
    env_file:
      - register.env

  redis:
    container_name: fc-retrieval-redis
    image: "redis:alpine"
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared
    restart: always



#  dbg:
#   image: busybox
#   #image: radial/busyboxplus:curl
#   container_name: dbg
#   stdin_open: true
#   tty: true
#   networks:
#     - shared
     
networks:
  shared:
