version: "3.8"
services:
  provider:
    image: ${PROVIDER_IMAGE:-consensys/fc-retrieval-provider:dev}
    container_name: provider
    networks:
      - shared
    ports:
      - "8081:8081"
    env_file:
      - provider.env
    depends_on:
      - register
      - gateway

  gateway:
    image: ${GATEWAY_IMAGE:-consensys/fc-retrieval-gateway:dev}
    container_name: gateway
    networks:
      - shared
    env_file:
      - gateway.env
    ports:
      - "80:80"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
    depends_on:
      - register

  register:
    image: ${REGISTER_IMAGE:-consensys/fc-retrieval-register:dev}
    container_name: register
    ports:
      - "8080:8080"
    networks:
      - shared
    restart: unless-stopped
    env_file:
      - register.env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - shared
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
     
networks:
  shared:
    name: shared
    external: true
